/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    api(libs.jakarta.persistence.jakarta.persistence.api)
    api(libs.io.jsonwebtoken.jjwt)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.postgresql.postgresql)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test)
    implementation(kotlin("stdlib-jdk8"))
}

group = "com.demo"
version = "0.0.1-SNAPSHOT"
description = "demo"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(22)
}